// Create World
MERGE (w:World {name: "Rivenwood"})

// Create Buildings as Sectors with Locations and Dimensions using Points
MERGE (hA1_1:Sector {name: "HouseA1-1", owner: "Elder Elara", description: "Elder Elara's House", location: point({x: 0, y: 0, z: 0}), dimensions: point({x: 500, y: 300, z: 400})})
MERGE (hA1_2:Sector {name: "HouseA1-2", owner: "Blacksmith Barin", description: "Blacksmith Barin's House", location: point({x: 600, y: 0, z: 0}), dimensions: point({x: 600, y: 350, z: 450})})
MERGE (hA2_1:Sector {name: "HouseA2-1", owner: "Farmer Finn", description: "Farmer Finn's House", location: point({x: 1200, y: 0, z: 0}), dimensions: point({x: 700, y: 400, z: 500})})
MERGE (hA2_2:Sector {name: "HouseA2-2", owner: "Healer Hera", description: "Healer Hera's House", location: point({x: 1800, y: 0, z: 0}), dimensions: point({x: 550, y: 300, z: 400})})
MERGE (hB1_1:Sector {name: "HouseB1-1", owner: "Merchant Morgan", description: "Merchant Morgan's House", location: point({x: 0, y: 700, z: 0}), dimensions: point({x: 600, y: 350, z: 450})})
MERGE (hB1_2:Sector {name: "HouseB1-2", owner: "Guard Captain Garen", description: "Guard Captain Garen's House", location: point({x: 600, y: 700, z: 0}), dimensions: point({x: 650, y: 380, z: 480})})
MERGE (hC1_1:Sector {name: "HouseC1-1", owner: "Carpenter Colin", description: "Carpenter Colin's House", location: point({x: 1200, y: 700, z: 0}), dimensions: point({x: 750, y: 400, z: 500})})
MERGE (hC1_2:Sector {name: "HouseC1-2", owner: "Tailor Talia", description: "Tailor Talia's House", location: point({x: 1800, y: 700, z: 0}), dimensions: point({x: 600, y: 350, z: 450})})
MERGE (hC2_1:Sector {name: "HouseC2-1", owner: "Baker Bella", description: "Baker Bella's House", location: point({x: 0, y: 1400, z: 0}), dimensions: point({x: 650, y: 380, z: 480})})
MERGE (hC2_2:Sector {name: "HouseC2-2", owner: "Fisherman Finn", description: "Fisherman Finn's House", location: point({x: 600, y: 1400, z: 0}), dimensions: point({x: 700, y: 400, z: 500})})
MERGE (hD1_1:Sector {name: "HouseD1-1", owner: "Shopkeeper Sara", description: "Shopkeeper Sara's Shop", location: point({x: 1200, y: 1400, z: 0}), dimensions: point({x: 800, y: 450, z: 550})})
MERGE (hD1_2:Sector {name: "HouseD1-2", owner: "Innkeeper Ian", description: "Innkeeper Ian's Inn", location: point({x: 1800, y: 1400, z: 0}), dimensions: point({x: 850, y: 480, z: 580})})
MERGE (hD2_1:Sector {name: "HouseD2-1", owner: "Craftsman Caleb", description: "Craftsman Caleb's Workshop", location: point({x: 0, y: 2100, z: 0}), dimensions: point({x: 750, y: 400, z: 500})})
MERGE (hD2_2:Sector {name: "HouseD2-2", owner: "Alchemist Alana", description: "Alchemist Alana's Alchemy Shop", location: point({x: 600, y: 2100, z: 0}), dimensions: point({x: 700, y: 400, z: 500})})
MERGE (hE1_1:Sector {name: "HouseE1-1", owner: "Sailor Sam", description: "Sailor Sam's House", location: point({x: 1200, y: 2100, z: 0}), dimensions: point({x: 650, y: 380, z: 480})})
MERGE (hE1_2:Sector {name: "HouseE1-2", owner: "Harbormaster Hank", description: "Harbormaster Hank's House", location: point({x: 1800, y: 2100, z: 0}), dimensions: point({x: 800, y: 450, z: 550})})

// Establish Relationships between World and Buildings
MERGE (w)-[:HAS_SECTOR]->(hA1_1)
MERGE (w)-[:HAS_SECTOR]->(hA1_2)
MERGE (w)-[:HAS_SECTOR]->(hA2_1)
MERGE (w)-[:HAS_SECTOR]->(hA2_2)
MERGE (w)-[:HAS_SECTOR]->(hB1_1)
MERGE (w)-[:HAS_SECTOR]->(hB1_2)
MERGE (w)-[:HAS_SECTOR]->(hC1_1)
MERGE (w)-[:HAS_SECTOR]->(hC1_2)
MERGE (w)-[:HAS_SECTOR]->(hC2_1)
MERGE (w)-[:HAS_SECTOR]->(hC2_2)
MERGE (w)-[:HAS_SECTOR]->(hD1_1)
MERGE (w)-[:HAS_SECTOR]->(hD1_2)
MERGE (w)-[:HAS_SECTOR]->(hD2_1)
MERGE (w)-[:HAS_SECTOR]->(hD2_2)
MERGE (w)-[:HAS_SECTOR]->(hE1_1)
MERGE (w)-[:HAS_SECTOR]->(hE1_2)

// Create Arenas within Buildings (Rooms or Functional Areas) with Points
MERGE (rA1_1_1:Arena {name: "Living Room", description: "Living Room of Elder Elara's House", location: point({x: 0, y: 0, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rA1_1_2:Arena {name: "Bedroom", description: "Bedroom of Elder Elara's House", location: point({x: 0, y: 200, z: 0}), dimensions: point({x: 150, y: 100, z: 100})})
MERGE (rA1_1_3:Arena {name: "Kitchen", description: "Kitchen of Elder Elara's House", location: point({x: 200, y: 0, z: 0}), dimensions: point({x: 150, y: 100, z: 100})})
MERGE (rA1_1_4:Arena {name: "Library", description: "Library of Elder Elara's House", location: point({x: 200, y: 200, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (hA1_1)-[:HAS_ARENA]->(rA1_1_1)
MERGE (hA1_1)-[:HAS_ARENA]->(rA1_1_2)
MERGE (hA1_1)-[:HAS_ARENA]->(rA1_1_3)
MERGE (hA1_1)-[:HAS_ARENA]->(rA1_1_4)

MERGE (rA1_2_1:Arena {name: "Forge", description: "Blacksmith Barin's Forge", location: point({x: 600, y: 0, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rA1_2_2:Arena {name: "Living Quarters", description: "Living Quarters of Blacksmith Barin", location: point({x: 600, y: 300, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rA1_2_3:Arena {name: "Storage Room", description: "Storage Room of Blacksmith Barin", location: point({x: 900, y: 0, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rA1_2_4:Arena {name: "Workshop", description: "Workshop of Blacksmith Barin", location: point({x: 900, y: 300, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (hA1_2)-[:HAS_ARENA]->(rA1_2_1)
MERGE (hA1_2)-[:HAS_ARENA]->(rA1_2_2)
MERGE (hA1_2)-[:HAS_ARENA]->(rA1_2_3)
MERGE (hA1_2)-[:HAS_ARENA]->(rA1_2_4)

// Add more arenas for other sectors as needed
MERGE (rA2_1_1:Arena {name: "Living Room", description: "Living Room of Farmer Finn's House", location: point({x: 1200, y: 0, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rA2_1_2:Arena {name: "Barn", description: "Barn of Farmer Finn's House", location: point({x: 1500, y: 0, z: 0}), dimensions: point({x: 400, y: 300, z: 250})})
MERGE (rA2_1_3:Arena {name: "Kitchen", description: "Kitchen of Farmer Finn's House", location: point({x: 1200, y: 200, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rA2_1_4:Arena {name: "Bedroom", description: "Bedroom of Farmer Finn's House", location: point({x: 1400, y: 200, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (hA2_1)-[:HAS_ARENA]->(rA2_1_1)
MERGE (hA2_1)-[:HAS_ARENA]->(rA2_1_2)
MERGE (hA2_1)-[:HAS_ARENA]->(rA2_1_3)
MERGE (hA2_1)-[:HAS_ARENA]->(rA2_1_4)

MERGE (rA2_2_1:Arena {name: "Herbal Room", description: "Herbal Room of Healer Hera", location: point({x: 1800, y: 0, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rA2_2_2:Arena {name: "Living Quarters", description: "Living Quarters of Healer Hera", location: point({x: 1800, y: 200, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rA2_2_3:Arena {name: "Kitchen", description: "Kitchen of Healer Hera", location: point({x: 2000, y: 0, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rA2_2_4:Arena {name: "Storage Room", description: "Storage Room of Healer Hera", location: point({x: 2000, y: 200, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rA2_2_5:Arena {name: "Garden", description: "Garden of Healer Hera", location: point({x: 1800, y: 400, z: 0}), dimensions: point({x: 300, y: 200, z: 150})})
MERGE (hA2_2)-[:HAS_ARENA]->(rA2_2_1)
MERGE (hA2_2)-[:HAS_ARENA]->(rA2_2_2)
MERGE (hA2_2)-[:HAS_ARENA]->(rA2_2_3)
MERGE (hA2_2)-[:HAS_ARENA]->(rA2_2_4)
MERGE (hA2_2)-[:HAS_ARENA]->(rA2_2_5)

MERGE (rB1_1_1:Arena {name: "Trading Room", description: "Trading Room of Merchant Morgan", location: point({x: 0, y: 700, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rB1_1_2:Arena {name: "Living Quarters", description: "Living Quarters of Merchant Morgan", location: point({x: 300, y: 700, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rB1_1_3:Arena {name: "Kitchen", description: "Kitchen of Merchant Morgan", location: point({x: 0, y: 900, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rB1_1_4:Arena {name: "Office", description: "Office of Merchant Morgan", location: point({x: 200, y: 900, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rB1_1_5:Arena {name: "Storage Room", description: "Storage Room of Merchant Morgan", location: point({x: 300, y: 1100, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (hB1_1)-[:HAS_ARENA]->(rB1_1_1)
MERGE (hB1_1)-[:HAS_ARENA]->(rB1_1_2)
MERGE (hB1_1)-[:HAS_ARENA]->(rB1_1_3)
MERGE (hB1_1)-[:HAS_ARENA]->(rB1_1_4)
MERGE (hB1_1)-[:HAS_ARENA]->(rB1_1_5)

MERGE (rB1_2_1:Arena {name: "Office", description: "Office of Guard Captain Garen", location: point({x: 600, y: 700, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rB1_2_2:Arena {name: "Living Quarters", description: "Living Quarters of Guard Captain Garen", location: point({x: 900, y: 700, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rB1_2_3:Arena {name: "Armory", description: "Armory of Guard Captain Garen", location: point({x: 600, y: 900, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rB1_2_4:Arena {name: "Training Room", description: "Training Room of Guard Captain Garen", location: point({x: 900, y: 900, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rB1_2_5:Arena {name: "Kitchen", description: "Kitchen of Guard Captain Garen", location: point({x: 600, y: 1100, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (hB1_2)-[:HAS_ARENA]->(rB1_2_1)
MERGE (hB1_2)-[:HAS_ARENA]->(rB1_2_2)
MERGE (hB1_2)-[:HAS_ARENA]->(rB1_2_3)
MERGE (hB1_2)-[:HAS_ARENA]->(rB1_2_4)
MERGE (hB1_2)-[:HAS_ARENA]->(rB1_2_5)

MERGE (rC1_1_1:Arena {name: "Workshop", description: "Workshop of Carpenter Colin", location: point({x: 1200, y: 700, z: 0}), dimensions: point({x: 400, y: 300, z: 250})})
MERGE (rC1_1_2:Arena {name: "Living Quarters", description: "Living Quarters of Carpenter Colin", location: point({x: 1600, y: 700, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rC1_1_3:Arena {name: "Storage Room", description: "Storage Room of Carpenter Colin", location: point({x: 1200, y: 1000, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rC1_1_4:Arena {name: "Kitchen", description: "Kitchen of Carpenter Colin", location: point({x: 1400, y: 1000, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rC1_1_5:Arena {name: "Showroom", description: "Showroom of Carpenter Colin", location: point({x: 1600, y: 1000, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (hC1_1)-[:HAS_ARENA]->(rC1_1_1)
MERGE (hC1_1)-[:HAS_ARENA]->(rC1_1_2)
MERGE (hC1_1)-[:HAS_ARENA]->(rC1_1_3)
MERGE (hC1_1)-[:HAS_ARENA]->(rC1_1_4)
MERGE (hC1_1)-[:HAS_ARENA]->(rC1_1_5)

MERGE (rC1_2_1:Arena {name: "Tailoring Room", description: "Tailoring Room of Tailor Talia", location: point({x: 1800, y: 700, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rC1_2_2:Arena {name: "Living Quarters", description: "Living Quarters of Tailor Talia", location: point({x: 2100, y: 700, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rC1_2_3:Arena {name: "Storage Room", description: "Storage Room of Tailor Talia", location: point({x: 1800, y: 900, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rC1_2_4:Arena {name: "Kitchen", description: "Kitchen of Tailor Talia", location: point({x: 2000, y: 900, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rC1_2_5:Arena {name: "Showroom", description: "Showroom of Tailor Talia", location: point({x: 2100, y: 1100, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (hC1_2)-[:HAS_ARENA]->(rC1_2_1)
MERGE (hC1_2)-[:HAS_ARENA]->(rC1_2_2)
MERGE (hC1_2)-[:HAS_ARENA]->(rC1_2_3)
MERGE (hC1_2)-[:HAS_ARENA]->(rC1_2_4)
MERGE (hC1_2)-[:HAS_ARENA]->(rC1_2_5)

MERGE (rC2_1_1:Arena {name: "Bakery", description: "Bakery of Baker Bella", location: point({x: 0, y: 1400, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rC2_1_2:Arena {name: "Living Quarters", description: "Living Quarters of Baker Bella", location: point({x: 300, y: 1400, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rC2_1_3:Arena {name: "Storage Room", description: "Storage Room of Baker Bella", location: point({x: 0, y: 1600, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rC2_1_4:Arena {name: "Kitchen", description: "Kitchen of Baker Bella", location: point({x: 200, y: 1600, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rC2_1_5:Arena {name: "Dining Room", description: "Dining Room of Baker Bella", location: point({x: 300, y: 1800, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (hC2_1)-[:HAS_ARENA]->(rC2_1_1)
MERGE (hC2_1)-[:HAS_ARENA]->(rC2_1_2)
MERGE (hC2_1)-[:HAS_ARENA]->(rC2_1_3)
MERGE (hC2_1)-[:HAS_ARENA]->(rC2_1_4)
MERGE (hC2_1)-[:HAS_ARENA]->(rC2_1_5)

MERGE (rC2_2_1:Arena {name: "Fishing Gear Room", description: "Fishing Gear Room of Fisherman Finn", location: point({x: 600, y: 1400, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rC2_2_2:Arena {name: "Living Quarters", description: "Living Quarters of Fisherman Finn", location: point({x: 900, y: 1400, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rC2_2_3:Arena {name: "Storage Room", description: "Storage Room of Fisherman Finn", location: point({x: 600, y: 1600, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rC2_2_4:Arena {name: "Kitchen", description: "Kitchen of Fisherman Finn", location: point({x: 800, y: 1600, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rC2_2_5:Arena {name: "Dining Room", description: "Dining Room of Fisherman Finn", location: point({x: 900, y: 1800, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (hC2_2)-[:HAS_ARENA]->(rC2_2_1)
MERGE (hC2_2)-[:HAS_ARENA]->(rC2_2_2)
MERGE (hC2_2)-[:HAS_ARENA]->(rC2_2_3)
MERGE (hC2_2)-[:HAS_ARENA]->(rC2_2_4)
MERGE (hC2_2)-[:HAS_ARENA]->(rC2_2_5)

MERGE (rD1_1_1:Arena {name: "Shop Floor", description: "Shop Floor of Shopkeeper Sara", location: point({x: 1200, y: 1400, z: 0}), dimensions: point({x: 400, y: 300, z: 250})})
MERGE (rD1_1_2:Arena {name: "Storage Room", description: "Storage Room of Shopkeeper Sara", location: point({x: 1600, y: 1400, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rD1_1_3:Arena {name: "Living Quarters", description: "Living Quarters of Shopkeeper Sara", location: point({x: 1200, y: 1700, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rD1_1_4:Arena {name: "Kitchen", description: "Kitchen of Shopkeeper Sara", location: point({x: 1400, y: 1700, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rD1_1_5:Arena {name: "Office", description: "Office of Shopkeeper Sara", location: point({x: 1600, y: 1900, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (hD1_1)-[:HAS_ARENA]->(rD1_1_1)
MERGE (hD1_1)-[:HAS_ARENA]->(rD1_1_2)
MERGE (hD1_1)-[:HAS_ARENA]->(rD1_1_3)
MERGE (hD1_1)-[:HAS_ARENA]->(rD1_1_4)
MERGE (hD1_1)-[:HAS_ARENA]->(rD1_1_5)

MERGE (rD1_2_1:Arena {name: "Common Room", description: "Common Room of Innkeeper Ian", location: point({x: 1800, y: 1400, z: 0}), dimensions: point({x: 400, y: 300, z: 250})})
MERGE (rD1_2_2:Arena {name: "Guest Rooms", description: "Guest Rooms of Innkeeper Ian", location: point({x: 2200, y: 1400, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rD1_2_3:Arena {name: "Dining Room", description: "Dining Room of Innkeeper Ian", location: point({x: 1800, y: 1700, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rD1_2_4:Arena {name: "Kitchen", description: "Kitchen of Innkeeper Ian", location: point({x: 2100, y: 1700, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rD1_2_5:Arena {name: "Storage Room", description: "Storage Room of Innkeeper Ian", location: point({x: 2400, y: 1700, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (hD1_2)-[:HAS_ARENA]->(rD1_2_1)
MERGE (hD1_2)-[:HAS_ARENA]->(rD1_2_2)
MERGE (hD1_2)-[:HAS_ARENA]->(rD1_2_3)
MERGE (hD1_2)-[:HAS_ARENA]->(rD1_2_4)
MERGE (hD1_2)-[:HAS_ARENA]->(rD1_2_5)

MERGE (rD2_1_1:Arena {name: "Workshop Floor", description: "Workshop Floor of Craftsman Caleb", location: point({x: 0, y: 2100, z: 0}), dimensions: point({x: 400, y: 300, z: 250})})
MERGE (rD2_1_2:Arena {name: "Living Quarters", description: "Living Quarters of Craftsman Caleb", location: point({x: 400, y: 2100, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rD2_1_3:Arena {name: "Storage Room", description: "Storage Room of Craftsman Caleb", location: point({x: 0, y: 2400, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rD2_1_4:Arena {name: "Kitchen", description: "Kitchen of Craftsman Caleb", location: point({x: 200, y: 2400, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rD2_1_5:Arena {name: "Showroom", description: "Showroom of Craftsman Caleb", location: point({x: 400, y: 2600, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (hD2_1)-[:HAS_ARENA]->(rD2_1_1)
MERGE (hD2_1)-[:HAS_ARENA]->(rD2_1_2)
MERGE (hD2_1)-[:HAS_ARENA]->(rD2_1_3)
MERGE (hD2_1)-[:HAS_ARENA]->(rD2_1_4)
MERGE (hD2_1)-[:HAS_ARENA]->(rD2_1_5)

MERGE (rD2_2_1:Arena {name: "Alchemy Lab", description: "Alchemy Lab of Alchemist Alana", location: point({x: 600, y: 2100, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rD2_2_2:Arena {name: "Storage Room", description: "Storage Room of Alchemist Alana", location: point({x: 900, y: 2100, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rD2_2_3:Arena {name: "Living Quarters", description: "Living Quarters of Alchemist Alana", location: point({x: 600, y: 2400, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rD2_2_4:Arena {name: "Kitchen", description: "Kitchen of Alchemist Alana", location: point({x: 900, y: 2400, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rD2_2_5:Arena {name: "Garden", description: "Garden of Alchemist Alana", location: point({x: 1200, y: 2400, z: 0}), dimensions: point({x: 400, y: 300, z: 250})})
MERGE (hD2_2)-[:HAS_ARENA]->(rD2_2_1)
MERGE (hD2_2)-[:HAS_ARENA]->(rD2_2_2)
MERGE (hD2_2)-[:HAS_ARENA]->(rD2_2_3)
MERGE (hD2_2)-[:HAS_ARENA]->(rD2_2_4)
MERGE (hD2_2)-[:HAS_ARENA]->(rD2_2_5)

MERGE (rE1_1_1:Arena {name: "Living Room", description: "Living Room of Sailor Sam's House", location: point({x: 1200, y: 2100, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rE1_1_2:Arena {name: "Bedroom", description: "Bedroom of Sailor Sam's House", location: point({x: 1500, y: 2100, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rE1_1_3:Arena {name: "Kitchen", description: "Kitchen of Sailor Sam's House", location: point({x: 1200, y: 2400, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rE1_1_4:Arena {name: "Storage Room", description: "Storage Room of Sailor Sam's House", location: point({x: 1400, y: 2400, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rE1_1_5:Arena {name: "Dining Room", description: "Dining Room of Sailor Sam's House", location: point({x: 1500, y: 2600, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (hE1_1)-[:HAS_ARENA]->(rE1_1_1)
MERGE (hE1_1)-[:HAS_ARENA]->(rE1_1_2)
MERGE (hE1_1)-[:HAS_ARENA]->(rE1_1_3)
MERGE (hE1_1)-[:HAS_ARENA]->(rE1_1_4)
MERGE (hE1_1)-[:HAS_ARENA]->(rE1_1_5)

MERGE (rE1_2_1:Arena {name: "Office", description: "Office of Harbormaster Hank", location: point({x: 1800, y: 2100, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rE1_2_2:Arena {name: "Living Quarters", description: "Living Quarters of Harbormaster Hank", location: point({x: 2100, y: 2100, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rE1_2_3:Arena {name: "Kitchen", description: "Kitchen of Harbormaster Hank", location: point({x: 1800, y: 2400, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rE1_2_4:Arena {name: "Storage Room", description: "Storage Room of Harbormaster Hank", location: point({x: 2000, y: 2400, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (rE1_2_5:Arena {name: "Dining Room", description: "Dining Room of Harbormaster Hank", location: point({x: 2100, y: 2600, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (hE1_2)-[:HAS_ARENA]->(rE1_2_1)
MERGE (hE1_2)-[:HAS_ARENA]->(rE1_2_2)
MERGE (hE1_2)-[:HAS_ARENA]->(rE1_2_3)
MERGE (hE1_2)-[:HAS_ARENA]->(rE1_2_4)
MERGE (hE1_2)-[:HAS_ARENA]->(rE1_2_5)


// Objects in Elder Elara's House (Library)
MERGE (oA1_1_1:Object {name: "Ancient Book", description: "An ancient book with knowledge of the town's history", location: point({x: 200, y: 200, z: 50})})
MERGE (oA1_1_2:Object {name: "Writing Desk", description: "A desk for writing and studying", location: point({x: 220, y: 220, z: 50})})
MERGE (oA1_1_3:Object {name: "Chair", description: "A wooden chair", location: point({x: 240, y: 240, z: 50})})
MERGE (rA1_1_4)-[:HAS_OBJECT]->(oA1_1_1)
MERGE (rA1_1_4)-[:HAS_OBJECT]->(oA1_1_2)
MERGE (rA1_1_4)-[:HAS_OBJECT]->(oA1_1_3)

// Objects in Blacksmith Barin's House (Forge)
MERGE (oA1_2_1:Object {name: "Blacksmith Hammer", description: "A hammer used by Blacksmith Barin", location: point({x: 600, y: 0, z: 50})})
MERGE (oA1_2_2:Object {name: "Anvil", description: "An anvil for forging", location: point({x: 620, y: 20, z: 50})})
MERGE (oA1_2_3:Object {name: "Forge", description: "A forge for heating metal", location: point({x: 640, y: 40, z: 50})})
MERGE (rA1_2_1)-[:HAS_OBJECT]->(oA1_2_1)
MERGE (rA1_2_1)-[:HAS_OBJECT]->(oA1_2_2)
MERGE (rA1_2_1)-[:HAS_OBJECT]->(oA1_2_3)

// Objects in Farmer Finn's House (Barn)
MERGE (oA2_1_1:Object {name: "Scythe", description: "A scythe used by Farmer Finn", location: point({x: 1500, y: 0, z: 50})})
MERGE (oA2_1_2:Object {name: "Hay Bale", description: "A bale of hay", location: point({x: 1520, y: 20, z: 50})})
MERGE (oA2_1_3:Object {name: "Pitchfork", description: "A pitchfork", location: point({x: 1540, y: 40, z: 50})})
MERGE (rA2_1_2)-[:HAS_OBJECT]->(oA2_1_1)
MERGE (rA2_1_2)-[:HAS_OBJECT]->(oA2_1_2)
MERGE (rA2_1_2)-[:HAS_OBJECT]->(oA2_1_3)

// Objects in Healer Hera's House (Herbal Room)
MERGE (oA2_2_1:Object {name: "Herb Collection", description: "A collection of herbs by Healer Hera", location: point({x: 2000, y: 0, z: 50})})
MERGE (oA2_2_2:Object {name: "Mortar and Pestle", description: "A mortar and pestle for grinding herbs", location: point({x: 2020, y: 20, z: 50})})
MERGE (oA2_2_3:Object {name: "Potion Bottles", description: "Bottles for storing potions", location: point({x: 2040, y: 40, z: 50})})
MERGE (rA2_2_1)-[:HAS_OBJECT]->(oA2_2_1)
MERGE (rA2_2_1)-[:HAS_OBJECT]->(oA2_2_2)
MERGE (rA2_2_1)-[:HAS_OBJECT]->(oA2_2_3)

// Objects in Merchant Morgan's House (Trading Room)
MERGE (oB1_1_1:Object {name: "Trade Ledger", description: "A ledger of trades by Merchant Morgan", location: point({x: 0, y: 700, z: 50})})
MERGE (oB1_1_2:Object {name: "Gold Coins", description: "A pile of gold coins", location: point({x: 20, y: 720, z: 50})})
MERGE (oB1_1_3:Object {name: "Merchant Scales", description: "Scales for weighing goods", location: point({x: 40, y: 740, z: 50})})
MERGE (rB1_1_1)-[:HAS_OBJECT]->(oB1_1_1)
MERGE (rB1_1_1)-[:HAS_OBJECT]->(oB1_1_2)
MERGE (rB1_1_1)-[:HAS_OBJECT]->(oB1_1_3)

// Objects in Guard Captain Garen's House (Armory)
MERGE (oB1_2_1:Object {name: "Sword", description: "A sword from the armory of Guard Captain Garen", location: point({x: 600, y: 900, z: 50})})
MERGE (oB1_2_2:Object {name: "Shield", description: "A shield from the armory", location: point({x: 620, y: 920, z: 50})})
MERGE (oB1_2_3:Object {name: "Armor", description: "A set of armor", location: point({x: 640, y: 940, z: 50})})
MERGE (rB1_2_3)-[:HAS_OBJECT]->(oB1_2_1)
MERGE (rB1_2_3)-[:HAS_OBJECT]->(oB1_2_2)
MERGE (rB1_2_3)-[:HAS_OBJECT]->(oB1_2_3)

// Objects in Carpenter Colin's House (Workshop)
MERGE (oC1_1_1:Object {name: "Woodworking Tools", description: "Tools used by Carpenter Colin", location: point({x: 1200, y: 700, z: 50})})
MERGE (oC1_1_2:Object {name: "Workbench", description: "A workbench for carpentry", location: point({x: 1220, y: 720, z: 50})})
MERGE (oC1_1_3:Object {name: "Wood Planks", description: "A stack of wood planks", location: point({x: 1240, y: 740, z: 50})})
MERGE (rC1_1_1)-[:HAS_OBJECT]->(oC1_1_1)
MERGE (rC1_1_1)-[:HAS_OBJECT]->(oC1_1_2)
MERGE (rC1_1_1)-[:HAS_OBJECT]->(oC1_1_3)

// Objects in Tailor Talia's House (Tailoring Room)
MERGE (oC1_2_1:Object {name: "Tailoring Supplies", description: "Supplies used by Tailor Talia", location: point({x: 1800, y: 700, z: 50})})
MERGE (oC1_2_2:Object {name: "Sewing Machine", description: "A sewing machine", location: point({x: 1820, y: 720, z: 50})})
MERGE (oC1_2_3:Object {name: "Fabric Rolls", description: "Rolls of fabric", location: point({x: 1840, y: 740, z: 50})})
MERGE (rC1_2_1)-[:HAS_OBJECT]->(oC1_2_1)
MERGE (rC1_2_1)-[:HAS_OBJECT]->(oC1_2_2)
MERGE (rC1_2_1)-[:HAS_OBJECT]->(oC1_2_3)

// Objects in Baker Bella's House (Bakery)
MERGE (oC2_1_1:Object {name: "Baking Ingredients", description: "Ingredients used by Baker Bella", location: point({x: 0, y: 1400, z: 50})})
MERGE (oC2_1_2:Object {name: "Oven", description: "An oven for baking", location: point({x: 20, y: 1420, z: 50})})
MERGE (oC2_1_3:Object {name: "Mixing Bowl", description: "A bowl for mixing ingredients", location: point({x: 40, y: 1440, z: 50})})
MERGE (rC2_1_1)-[:HAS_OBJECT]->(oC2_1_1)
MERGE (rC2_1_1)-[:HAS_OBJECT]->(oC2_1_2)
MERGE (rC2_1_1)-[:HAS_OBJECT]->(oC2_1_3)

// Objects in Fisherman Finn's House (Fishing Gear Room)
MERGE (oC2_2_1:Object {name: "Fishing Net", description: "A net used by Fisherman Finn", location: point({x: 600, y: 1400, z: 50})})
MERGE (oC2_2_2:Object {name: "Fishing Rod", description: "A fishing rod", location: point({x: 620, y: 1420, z: 50})})
MERGE (oC2_2_3:Object {name: "Tackle Box", description: "A box of fishing tackle", location: point({x: 640, y: 1440, z: 50})})
MERGE (rC2_2_1)-[:HAS_OBJECT]->(oC2_2_1)
MERGE (rC2_2_1)-[:HAS_OBJECT]->(oC2_2_2)
MERGE (rC2_2_1)-[:HAS_OBJECT]->(oC2_2_3)

// Objects in Shopkeeper Sara's Shop (Shop Floor)
MERGE (oD1_1_1:Object {name: "Cash Register", description: "A cash register from Shopkeeper Sara's shop", location: point({x: 1200, y: 1400, z: 50})})
MERGE (oD1_1_2:Object {name: "Display Case", description: "A display case for goods", location: point({x: 1220, y: 1420, z: 50})})
MERGE (oD1_1_3:Object {name: "Shelves", description: "Shelves for displaying items", location: point({x: 1240, y: 1440, z: 50})})
MERGE (rD1_1_1)-[:HAS_OBJECT]->(oD1_1_1)
MERGE (rD1_1_1)-[:HAS_OBJECT]->(oD1_1_2)
MERGE (rD1_1_1)-[:HAS_OBJECT]->(oD1_1_3)

// Objects in Innkeeper Ian's Inn (Common Room)
MERGE (oD1_2_1:Object {name: "Guest Register", description: "A register of guests at Innkeeper Ian's inn", location: point({x: 1800, y: 1400, z: 50})})
MERGE (oD1_2_2:Object {name: "Common Table", description: "A table for guests", location: point({x: 1820, y: 1420, z: 50})})
MERGE (oD1_2_3:Object {name: "Fireplace", description: "A fireplace to keep the common room warm", location: point({x: 1840, y: 1440, z: 50})})
MERGE (rD1_2_1)-[:HAS_OBJECT]->(oD1_2_1)
MERGE (rD1_2_1)-[:HAS_OBJECT]->(oD1_2_2)
MERGE (rD1_2_1)-[:HAS_OBJECT]->(oD1_2_3)

// Objects in Craftsman Caleb's Workshop (Workshop Floor)
MERGE (oD2_1_1:Object {name: "Crafted Items", description: "Items crafted by Craftsman Caleb", location: point({x: 0, y: 2100, z: 50})})
MERGE (oD2_1_2:Object {name: "Workbench", description: "A bench for crafting", location: point({x: 20, y: 2120, z: 50})})
MERGE (oD2_1_3:Object {name: "Tools", description: "Various crafting tools", location: point({x: 40, y: 2140, z: 50})})
MERGE (rD2_1_1)-[:HAS_OBJECT]->(oD2_1_1)
MERGE (rD2_1_1)-[:HAS_OBJECT]->(oD2_1_2)
MERGE (rD2_1_1)-[:HAS_OBJECT]->(oD2_1_3)

// Objects in Alchemist Alana's Alchemy Shop (Alchemy Lab)
MERGE (oD2_2_1:Object {name: "Alchemy Ingredients", description: "Ingredients used by Alchemist Alana", location: point({x: 600, y: 2100, z: 50})})
MERGE (oD2_2_2:Object {name: "Alchemy Table", description: "A table for alchemical experiments", location: point({x: 620, y: 2120, z: 50})})
MERGE (oD2_2_3:Object {name: "Potion Bottles", description: "Bottles for storing potions", location: point({x: 640, y: 2140, z: 50})})
MERGE (rD2_2_1)-[:HAS_OBJECT]->(oD2_2_1)
MERGE (rD2_2_1)-[:HAS_OBJECT]->(oD2_2_2)
MERGE (rD2_2_1)-[:HAS_OBJECT]->(oD2_2_3)

// Objects in Sailor Sam's House (Living Room)
MERGE (oE1_1_1:Object {name: "Sailing Charts", description: "Charts used by Sailor Sam", location: point({x: 1200, y: 2100, z: 50})})
MERGE (oE1_1_2:Object {name: "Sextant", description: "A tool for navigation", location: point({x: 1220, y: 2120, z: 50})})
MERGE (oE1_1_3:Object {name: "Compass", description: "A compass for navigation", location: point({x: 1240, y: 2140, z: 50})})
MERGE (rE1_1_1)-[:HAS_OBJECT]->(oE1_1_1)
MERGE (rE1_1_1)-[:HAS_OBJECT]->(oE1_1_2)
MERGE (rE1_1_1)-[:HAS_OBJECT]->(oE1_1_3)

// Objects in Harbormaster Hank's House (Office)
MERGE (oE1_2_1:Object {name: "Harbor Records", description: "Records of the harbor kept by Harbormaster Hank", location: point({x: 1800, y: 2100, z: 50})})
MERGE (oE1_2_2:Object {name: "Ledger", description: "A ledger of harbor activities", location: point({x: 1820, y: 2120, z: 50})})
MERGE (oE1_2_3:Object {name: "Map", description: "A map of the harbor", location: point({x: 1840, y: 2140, z: 50})})
MERGE (rE1_2_1)-[:HAS_OBJECT]->(oE1_2_1)
MERGE (rE1_2_1)-[:HAS_OBJECT]->(oE1_2_2)
MERGE (rE1_2_1)-[:HAS_OBJECT]->(oE1_2_3)









// Create World if not already exists
MERGE (w:World {name: "Rivenwood"})

// Create Essential Buildings as Sectors with Locations and Dimensions using Points
MERGE (th:Sector {name: "Town Hall", description: "Central administrative building where the town's leaders meet and manage town affairs", location: point({x: 100, y: 100, z: 0}), dimensions: point({x: 500, y: 400, z: 300})})
MERGE (gb:Sector {name: "Guard Barracks", description: "Housing for the town's guard force, equipped with training grounds", location: point({x: 200, y: 100, z: 0}), dimensions: point({x: 600, y: 400, z: 300})})
MERGE (wt1:Sector {name: "Watchtower North", description: "Watchtower for lookout and defense at the northern perimeter", location: point({x: 300, y: 100, z: 0}), dimensions: point({x: 200, y: 200, z: 200})})
MERGE (wt2:Sector {name: "Watchtower South", description: "Watchtower for lookout and defense at the southern perimeter", location: point({x: 400, y: 100, z: 0}), dimensions: point({x: 200, y: 200, z: 200})})
MERGE (mp:Sector {name: "Marketplace", description: "Open area where traders and merchants set up stalls to sell goods", location: point({x: 500, y: 100, z: 0}), dimensions: point({x: 800, y: 600, z: 400})})
MERGE (wh:Sector {name: "Warehouse", description: "Storage for goods and trade supplies, especially those arriving by ship", location: point({x: 600, y: 100, z: 0}), dimensions: point({x: 700, y: 500, z: 300})})
MERGE (bf:Sector {name: "Blacksmith Forge", description: "Essential for producing and repairing tools, weapons, and armor", location: point({x: 700, y: 100, z: 0}), dimensions: point({x: 600, y: 400, z: 300})})
MERGE (tv:Sector {name: "Tavern", description: "Social gathering place for residents and travelers, serving food and drink", location: point({x: 800, y: 100, z: 0}), dimensions: point({x: 900, y: 600, z: 400})})
MERGE (ch:Sector {name: "Church", description: "Place of worship and community gathering, often the heart of social life", location: point({x: 900, y: 100, z: 0}), dimensions: point({x: 700, y: 500, z: 300})})
MERGE (sh:Sector {name: "Schoolhouse", description: "Building for educating the children of the town", location: point({x: 1000, y: 100, z: 0}), dimensions: point({x: 600, y: 400, z: 300})})
MERGE (ap:Sector {name: "Apothecary", description: "Provides medicinal herbs and remedies, crucial for health care", location: point({x: 1100, y: 100, z: 0}), dimensions: point({x: 600, y: 400, z: 300})})
MERGE (bs:Sector {name: "Butcher Shop", description: "Prepares and sells meat products", location: point({x: 1200, y: 100, z: 0}), dimensions: point({x: 700, y: 500, z: 300})})
MERGE (ml:Sector {name: "Mill", description: "Grinds grain into flour, essential for food production", location: point({x: 1300, y: 100, z: 0}), dimensions: point({x: 600, y: 400, z: 300})})
MERGE (sy:Sector {name: "Shipyard", description: "Facility for building and repairing ships", location: point({x: 1400, y: 100, z: 0}), dimensions: point({x: 900, y: 600, z: 400})})
MERGE (fm:Sector {name: "Fish Market", description: "Sells fresh fish and seafood, crucial for the town's diet", location: point({x: 1500, y: 100, z: 0}), dimensions: point({x: 800, y: 600, z: 400})})
MERGE (hm:Sector {name: "Harbormaster’s Office", description: "Manages dock operations and maritime activities", location: point({x: 1600, y: 100, z: 0}), dimensions: point({x: 600, y: 400, z: 300})})

// Establish Relationships between World and Essential Buildings
MERGE (w)-[:HAS_SECTOR]->(th)
MERGE (w)-[:HAS_SECTOR]->(gb)
MERGE (w)-[:HAS_SECTOR]->(wt1)
MERGE (w)-[:HAS_SECTOR]->(wt2)
MERGE (w)-[:HAS_SECTOR]->(mp)
MERGE (w)-[:HAS_SECTOR]->(wh)
MERGE (w)-[:HAS_SECTOR]->(bf)
MERGE (w)-[:HAS_SECTOR]->(tv)
MERGE (w)-[:HAS_SECTOR]->(ch)
MERGE (w)-[:HAS_SECTOR]->(sh)
MERGE (w)-[:HAS_SECTOR]->(ap)
MERGE (w)-[:HAS_SECTOR]->(bs)
MERGE (w)-[:HAS_SECTOR]->(ml)
MERGE (w)-[:HAS_SECTOR]->(sy)
MERGE (w)-[:HAS_SECTOR]->(fm)
MERGE (w)-[:HAS_SECTOR]->(hm)

// Create Arenas within Essential Buildings (Rooms or Functional Areas)
MERGE (rth_1:Arena {name: "Meeting Hall", description: "Main meeting hall in the Town Hall", location: point({x: 100, y: 100, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rth_2:Arena {name: "Office", description: "Office in the Town Hall", location: point({x: 100, y: 300, z: 0}), dimensions: point({x: 200, y: 100, z: 100})})
MERGE (rth_3:Arena {name: "Records Room", description: "Records Room in the Town Hall", location: point({x: 200, y: 100, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (th)-[:HAS_ARENA]->(rth_1)
MERGE (th)-[:HAS_ARENA]->(rth_2)
MERGE (th)-[:HAS_ARENA]->(rth_3)

MERGE (rgb_1:Arena {name: "Barracks", description: "Sleeping quarters for the guards", location: point({x: 200, y: 100, z: 0}), dimensions: point({x: 400, y: 300, z: 300})})
MERGE (rgb_2:Arena {name: "Training Ground", description: "Training ground for the guards", location: point({x: 200, y: 400, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rgb_3:Arena {name: "Armory", description: "Armory in the Guard Barracks", location: point({x: 400, y: 100, z: 0}), dimensions: point({x: 200, y: 150, z: 150})})
MERGE (gb)-[:HAS_ARENA]->(rgb_1)
MERGE (gb)-[:HAS_ARENA]->(rgb_2)
MERGE (gb)-[:HAS_ARENA]->(rgb_3)

MERGE (rwt1_1:Arena {name: "Observation Deck", description: "Observation Deck of the North Watchtower", location: point({x: 300, y: 100, z: 0}), dimensions: point({x: 200, y: 100, z: 100})})
MERGE (rwt1_2:Arena {name: "Guard Room", description: "Guard Room of the North Watchtower", location: point({x: 300, y: 200, z: 0}), dimensions: point({x: 200, y: 100, z: 100})})
MERGE (wt1)-[:HAS_ARENA]->(rwt1_1)
MERGE (wt1)-[:HAS_ARENA]->(rwt1_2)

MERGE (rwt2_1:Arena {name: "Observation Deck", description: "Observation Deck of the South Watchtower", location: point({x: 400, y: 100, z: 0}), dimensions: point({x: 200, y: 100, z: 100})})
MERGE (rwt2_2:Arena {name: "Guard Room", description: "Guard Room of the South Watchtower", location: point({x: 400, y: 200, z: 0}), dimensions: point({x: 200, y: 100, z: 100})})
MERGE (wt2)-[:HAS_ARENA]->(rwt2_1)
MERGE (wt2)-[:HAS_ARENA]->(rwt2_2)

MERGE (rmp_1:Arena {name: "Stalls", description: "Stalls in the Marketplace", location: point({x: 500, y: 100, z: 0}), dimensions: point({x: 400, y: 200, z: 200})})
MERGE (rmp_2:Arena {name: "Central Plaza", description: "Central Plaza of the Marketplace", location: point({x: 700, y: 100, z: 0}), dimensions: point({x: 400, y: 300, z: 300})})
MERGE (mp)-[:HAS_ARENA]->(rmp_1)
MERGE (mp)-[:HAS_ARENA]->(rmp_2)

MERGE (rwh_1:Arena {name: "Storage Room", description: "Storage Room in the Warehouse", location: point({x: 600, y: 100, z: 0}), dimensions: point({x: 400, y: 200, z: 200})})
MERGE (rwh_2:Arena {name: "Loading Dock", description: "Loading Dock in the Warehouse", location: point({x: 600, y: 300, z: 0}), dimensions: point({x: 400, y: 200, z: 200})})
MERGE (wh)-[:HAS_ARENA]->(rwh_1)
MERGE (wh)-[:HAS_ARENA]->(rwh_2)

MERGE (rbf_1:Arena {name: "Forge Room", description: "Forge Room in the Blacksmith Forge", location: point({x: 700, y: 100, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rbf_2:Arena {name: "Storage Room", description: "Storage Room in the Blacksmith Forge", location: point({x: 700, y: 300, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rbf_3:Arena {name: "Workshop", description: "Workshop in the Blacksmith Forge", location: point({x: 700, y: 500, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (bf)-[:HAS_ARENA]->(rbf_1)
MERGE (bf)-[:HAS_ARENA]->(rbf_2)
MERGE (bf)-[:HAS_ARENA]->(rbf_3)

MERGE (rtv_1:Arena {name: "Common Room", description: "Common Room in the Tavern", location: point({x: 800, y: 100, z: 0}), dimensions: point({x: 400, y: 200, z: 200})})
MERGE (rtv_2:Arena {name: "Dining Area", description: "Dining Area in the Tavern", location: point({x: 800, y: 300, z: 0}), dimensions: point({x: 400, y: 200, z: 200})})
MERGE (rtv_3:Arena {name: "Kitchen", description: "Kitchen in the Tavern", location: point({x: 800, y: 500, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rtv_4:Arena {name: "Guest Rooms", description: "Guest Rooms in the Tavern", location: point({x: 800, y: 700, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (tv)-[:HAS_ARENA]->(rtv_1)
MERGE (tv)-[:HAS_ARENA]->(rtv_2)
MERGE (tv)-[:HAS_ARENA]->(rtv_3)
MERGE (tv)-[:HAS_ARENA]->(rtv_4)

MERGE (rch_1:Arena {name: "Nave", description: "Nave in the Church", location: point({x: 900, y: 100, z: 0}), dimensions: point({x: 400, y: 200, z: 200})})
MERGE (rch_2:Arena {name: "Altar", description: "Altar in the Church", location: point({x: 900, y: 300, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rch_3:Arena {name: "Bell Tower", description: "Bell Tower in the Church", location: point({x: 900, y: 500, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (ch)-[:HAS_ARENA]->(rch_1)
MERGE (ch)-[:HAS_ARENA]->(rch_2)
MERGE (ch)-[:HAS_ARENA]->(rch_3)

MERGE (rsh_1:Arena {name: "Classroom", description: "Classroom in the Schoolhouse", location: point({x: 1000, y: 100, z: 0}), dimensions: point({x: 400, y: 200, z: 200})})
MERGE (rsh_2:Arena {name: "Library", description: "Library in the Schoolhouse", location: point({x: 1000, y: 300, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rsh_3:Arena {name: "Playground", description: "Playground in the Schoolhouse", location: point({x: 1000, y: 500, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (sh)-[:HAS_ARENA]->(rsh_1)
MERGE (sh)-[:HAS_ARENA]->(rsh_2)
MERGE (sh)-[:HAS_ARENA]->(rsh_3)

MERGE (rap_1:Arena {name: "Herb Room", description: "Herb Room in the Apothecary", location: point({x: 1100, y: 100, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rap_2:Arena {name: "Consultation Room", description: "Consultation Room in the Apothecary", location: point({x: 1100, y: 300, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rap_3:Arena {name: "Storage Room", description: "Storage Room in the Apothecary", location: point({x: 1100, y: 500, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (ap)-[:HAS_ARENA]->(rap_1)
MERGE (ap)-[:HAS_ARENA]->(rap_2)
MERGE (ap)-[:HAS_ARENA]->(rap_3)

MERGE (rbs_1:Arena {name: "Butchery", description: "Butchery in the Butcher Shop", location: point({x: 1200, y: 100, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rbs_2:Arena {name: "Storage Room", description: "Storage Room in the Butcher Shop", location: point({x: 1200, y: 300, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rbs_3:Arena {name: "Shop Floor", description: "Shop Floor in the Butcher Shop", location: point({x: 1200, y: 500, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (bs)-[:HAS_ARENA]->(rbs_1)
MERGE (bs)-[:HAS_ARENA]->(rbs_2)
MERGE (bs)-[:HAS_ARENA]->(rbs_3)

MERGE (rml_1:Arena {name: "Mill Room", description: "Mill Room in the Mill", location: point({x: 1300, y: 100, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rml_2:Arena {name: "Storage Room", description: "Storage Room in the Mill", location: point({x: 1300, y: 300, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rml_3:Arena {name: "Office", description: "Office in the Mill", location: point({x: 1300, y: 500, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (ml)-[:HAS_ARENA]->(rml_1)
MERGE (ml)-[:HAS_ARENA]->(rml_2)
MERGE (ml)-[:HAS_ARENA]->(rml_3)

MERGE (rsy_1:Arena {name: "Ship Building Area", description: "Ship Building Area in the Shipyard", location: point({x: 1400, y: 100, z: 0}), dimensions: point({x: 400, y: 200, z: 200})})
MERGE (rsy_2:Arena {name: "Repair Dock", description: "Repair Dock in the Shipyard", location: point({x: 1400, y: 300, z: 0}), dimensions: point({x: 400, y: 200, z: 200})})
MERGE (rsy_3:Arena {name: "Storage Room", description: "Storage Room in the Shipyard", location: point({x: 1400, y: 500, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (sy)-[:HAS_ARENA]->(rsy_1)
MERGE (sy)-[:HAS_ARENA]->(rsy_2)
MERGE (sy)-[:HAS_ARENA]->(rsy_3)

MERGE (rfm_1:Arena {name: "Fish Stalls", description: "Fish Stalls in the Fish Market", location: point({x: 1500, y: 100, z: 0}), dimensions: point({x: 400, y: 200, z: 200})})
MERGE (rfm_2:Arena {name: "Auction Area", description: "Auction Area in the Fish Market", location: point({x: 1500, y: 300, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rfm_3:Arena {name: "Storage Room", description: "Storage Room in the Fish Market", location: point({x: 1500, y: 500, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (fm)-[:HAS_ARENA]->(rfm_1)
MERGE (fm)-[:HAS_ARENA]->(rfm_2)
MERGE (fm)-[:HAS_ARENA]->(rfm_3)

MERGE (rhm_1:Arena {name: "Office", description: "Office of the Harbormaster", location: point({x: 1600, y: 100, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rhm_2:Arena {name: "Storage Room", description: "Storage Room in the Harbormaster’s Office", location: point({x: 1600, y: 300, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (rhm_3:Arena {name: "Meeting Room", description: "Meeting Room in the Harbormaster’s Office", location: point({x: 1600, y: 500, z: 0}), dimensions: point({x: 300, y: 200, z: 200})})
MERGE (hm)-[:HAS_ARENA]->(rhm_1)
MERGE (hm)-[:HAS_ARENA]->(rhm_2)
MERGE (hm)-[:HAS_ARENA]->(rhm_3)

// Create Essential Objects for Arenas
// Town Hall
MERGE (o_th_1:Object {name: "Table", description: "Large meeting table", location: point({x: 100, y: 100, z: 50})})
MERGE (o_th_2:Object {name: "Chair", description: "Comfortable chairs for meetings", location: point({x: 100, y: 150, z: 50})})
MERGE (o_th_3:Object {name: "Bookshelf", description: "Bookshelf containing town records", location: point({x: 200, y: 100, z: 50})})
MERGE (rth_1)-[:HAS_OBJECT]->(o_th_1)
MERGE (rth_1)-[:HAS_OBJECT]->(o_th_2)
MERGE (rth_3)-[:HAS_OBJECT]->(o_th_3)

// Guard Barracks
MERGE (o_gb_1:Object {name: "Bunk Bed", description: "Beds for the guards", location: point({x: 200, y: 100, z: 50})})
MERGE (o_gb_2:Object {name: "Weapon Rack", description: "Rack for storing weapons", location: point({x: 400, y: 100, z: 50})})
MERGE (o_gb_3:Object {name: "Training Dummy", description: "Dummy for training exercises", location: point({x: 200, y: 400, z: 50})})
MERGE (rgb_1)-[:HAS_OBJECT]->(o_gb_1)
MERGE (rgb_2)-[:HAS_OBJECT]->(o_gb_3)
MERGE (rgb_3)-[:HAS_OBJECT]->(o_gb_2)

// Watchtowers
MERGE (o_wt_1:Object {name: "Telescope", description: "Telescope for observation", location: point({x: 300, y: 100, z: 50})})
MERGE (o_wt_2:Object {name: "Signal Torch", description: "Torch for signaling", location: point({x: 300, y: 150, z: 50})})
MERGE (rwt1_1)-[:HAS_OBJECT]->(o_wt_1)
MERGE (rwt1_1)-[:HAS_OBJECT]->(o_wt_2)
MERGE (rwt2_1)-[:HAS_OBJECT]->(o_wt_1)
MERGE (rwt2_1)-[:HAS_OBJECT]->(o_wt_2)

// Marketplace
MERGE (o_mp_1:Object {name: "Market Stall", description: "Stalls for vendors", location: point({x: 500, y: 100, z: 50})})
MERGE (o_mp_2:Object {name: "Fountain", description: "Central fountain in the marketplace", location: point({x: 700, y: 100, z: 50})})
MERGE (rmp_1)-[:HAS_OBJECT]->(o_mp_1)
MERGE (rmp_2)-[:HAS_OBJECT]->(o_mp_2)

// Warehouse
MERGE (o_wh_1:Object {name: "Crate", description: "Storage crates", location: point({x: 600, y: 100, z: 50})})
MERGE (o_wh_2:Object {name: "Pallet", description: "Wooden pallets for goods", location: point({x: 600, y: 150, z: 50})})
MERGE (rwh_1)-[:HAS_OBJECT]->(o_wh_1)
MERGE (rwh_1)-[:HAS_OBJECT]->(o_wh_2)

// Blacksmith Forge
MERGE (o_bf_1:Object {name: "Anvil", description: "Anvil for blacksmithing", location: point({x: 700, y: 100, z: 50})})
MERGE (o_bf_2:Object {name: "Forge", description: "Forge for heating metal", location: point({x: 700, y: 150, z: 50})})
MERGE (o_bf_3:Object {name: "Hammer", description: "Hammer for blacksmithing", location: point({x: 700, y: 200, z: 50})})
MERGE (rbf_1)-[:HAS_OBJECT]->(o_bf_1)
MERGE (rbf_1)-[:HAS_OBJECT]->(o_bf_2)
MERGE (rbf_1)-[:HAS_OBJECT]->(o_bf_3)

// Tavern
MERGE (o_tv_1:Object {name: "Bar Counter", description: "Counter for serving drinks", location: point({x: 800, y: 100, z: 50})})
MERGE (o_tv_2:Object {name: "Table", description: "Dining tables", location: point({x: 800, y: 150, z: 50})})
MERGE (o_tv_3:Object {name: "Bed", description: "Beds in guest rooms", location: point({x: 800, y: 500, z: 50})})
MERGE (rtv_1)-[:HAS_OBJECT]->(o_tv_1)
MERGE (rtv_2)-[:HAS_OBJECT]->(o_tv_2)
MERGE (rtv_4)-[:HAS_OBJECT]->(o_tv_3)

// Church
MERGE (o_ch_1:Object {name: "Altar", description: "Altar for religious ceremonies", location: point({x: 900, y: 300, z: 50})})
MERGE (o_ch_2:Object {name: "Pew", description: "Seating for congregation", location: point({x: 900, y: 100, z: 50})})
MERGE (rch_2)-[:HAS_OBJECT]->(o_ch_1)
MERGE (rch_1)-[:HAS_OBJECT]->(o_ch_2)

// Schoolhouse
MERGE (o_sh_1:Object {name: "Desk", description: "Desks for students", location: point({x: 1000, y: 100, z: 50})})
MERGE (o_sh_2:Object {name: "Blackboard", description: "Blackboard for teaching", location: point({x: 1000, y: 150, z: 50})})
MERGE (rsh_1)-[:HAS_OBJECT]->(o_sh_1)
MERGE (rsh_1)-[:HAS_OBJECT]->(o_sh_2)

// Apothecary
MERGE (o_ap_1:Object {name: "Herb Cabinet", description: "Cabinet for storing herbs", location: point({x: 1100, y: 100, z: 50})})
MERGE (o_ap_2:Object {name: "Mortar and Pestle", description: "Used for grinding herbs", location: point({x: 1100, y: 150, z: 50})})
MERGE (rap_1)-[:HAS_OBJECT]->(o_ap_1)
MERGE (rap_1)-[:HAS_OBJECT]->(o_ap_2)

// Butcher Shop
MERGE (o_bs_1:Object {name: "Butcher Block", description: "Block for cutting meat", location: point({x: 1200, y: 100, z: 50})})
MERGE (o_bs_2:Object {name: "Meat Hook", description: "Hooks for hanging meat", location: point({x: 1200, y: 150, z: 50})})
MERGE (rbs_1)-[:HAS_OBJECT]->(o_bs_1)
MERGE (rbs_1)-[:HAS_OBJECT]->(o_bs_2)

// Mill
MERGE (o_ml_1:Object {name: "Millstone", description: "Millstone for grinding grain", location: point({x: 1300, y: 100, z: 50})})
MERGE (o_ml_2:Object {name: "Sack of Grain", description: "Sacks of grain for milling", location: point({x: 1300, y: 150, z: 50})})
MERGE (rml_1)-[:HAS_OBJECT]->(o_ml_1)
MERGE (rml_1)-[:HAS_OBJECT]->(o_ml_2)

// Shipyard
MERGE (o_sy_1:Object {name: "Dry Dock", description: "Dry dock for shipbuilding", location: point({x: 1400, y: 100, z: 50})})
MERGE (o_sy_2:Object {name: "Crane", description: "Crane for lifting heavy parts", location: point({x: 1400, y: 150, z: 50})})
MERGE (rsy_1)-[:HAS_OBJECT]->(o_sy_1)
MERGE (rsy_1)-[:HAS_OBJECT]->(o_sy_2)

// Fish Market
MERGE (o_fm_1:Object {name: "Fish Stall", description: "Stalls for selling fish", location: point({x: 1500, y: 100, z: 50})})
MERGE (o_fm_2:Object {name: "Ice Box", description: "Boxes for keeping fish fresh", location: point({x: 1500, y: 150, z: 50})})
MERGE (rfm_1)-[:HAS_OBJECT]->(o_fm_1)
MERGE (rfm_1)-[:HAS_OBJECT]->(o_fm_2)

// Harbormaster’s Office
MERGE (o_hm_1:Object {name: "Logbook", description: "Logbook for recording ship arrivals and departures", location: point({x: 1600, y: 100, z: 50})})
MERGE (o_hm_2:Object {name: "Map", description: "Map of the harbor and surrounding waters", location: point({x: 1600, y: 150, z: 50})})
MERGE (rhm_1)-[:HAS_OBJECT]->(o_hm_1)
MERGE (rhm_1)-[:HAS_OBJECT]->(o_hm_2)
