version: '3'

services:
  app:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - database
    volumes:
      - .:/app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    networks:
      - app-net

  database: 
    image: neo4j:enterprise
    restart: always
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins

    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_apoc_uuid_node_enabled=true
      - NEO4J_apoc_uuid_relationship_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_useneo4jconfig=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    networks:
      - app-net

volumes:
  database:

networks:
  app-net: